language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

env:
  - NODE_ENV=test

script:
    - yarn validate

notifications:
  email:
    recipients:
      - jaime@waavi.com
      - alejandro@waavi.com
      - adrian@waavi.com
      - carlos@waavi.com
    on_success: change
    on_failure: always
