language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

env:
  - NODE_ENV=test VUE_APP_PROJECT_NAME=VueWCharts

script:
    - yarn test && yarn lint

notifications:
  email:
    recipients:
      - jaime@waavi.com
      - alejandro@waavi.com
      - adrian@waavi.com
    on_success: change
    on_failure: always
